name: Deployment

on:
  push:
    branches:
      - dev
      - testing
      - staging
      - production
      - hotfix
jobs:
EnvSelection:
runs-on: ubuntu-latest
rules:

- if: github.ref == 'refs/heads/dev-feature' 
  Development:
    runs-on: ubuntu-latest
    # run this job only for the Dev branch
    environment: 
      name: Development
      url: https://github.com
    steps:
      - name: deploy to Development
        run: echo "Hello Development!"
        # ...deployment-specific steps

- if: github.ref == 'refs/heads/dev' 
  Testing:
    runs-on: ubuntu-latest
    environment:
      name: Testing
      url: https://github.com
    steps:
      - name: deploy to Testing
        run: echo "Hello Testing!"
        # ...deployment-specific steps

- if: github.ref == 'refs/heads/testing'       
  Staging:
    runs-on: ubuntu-latest
    environment: 
      name: Staging
      url: https://github.com
    steps:
      - name: deploy to Staging
        run: echo "Hello Staging!"
        # ...deployment-specific steps

- if: github.ref == 'refs/heads/staging' 
  Production:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://github.com
    steps:
      - name: deploy to Staging
        run: echo "Hello Staging!"
        # ...deployment-specific steps
