name: Deployment

on:
  push:
    branches:
      - Dev
      - Testing
      - Staging
      - Prod
      - Hotfix
jobs:
  Development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/DevFeature' 
    # run this job only for the Dev branch
    environment: 
      name: Development
      url: https://github.com
    steps:
      - name: deploy to Development
        run: echo "Hello Development!"
        # ...deployment-specific steps

  Testing:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Dev' 
    environment:
      name: Testing
      url: https://github.com
    steps:
      - name: deploy to Testing
        run: echo "Hello Testing!"
        # ...deployment-specific steps

  Staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Testing' 
    environment: 
      name: Staging
      url: https://github.com
    steps:
      - name: deploy to Staging
        run: echo "Hello Staging!"
        # ...deployment-specific steps

  Production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Staging' 
    environment: 
      name: Production
      url: https://github.com
    steps:
      - name: deploy to Staging
        run: echo "Hello Staging!"
        # ...deployment-specific steps
